[package]
name = "chess-attempt-1"
version = "0.1.0"
authors = ["melvinj <13897+melvinj@users.noreply.gits-15.sys.kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
